import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  designer: [
    'intro',
    'designer/quick-start',
    {
      type: 'category',
      label: '接入指南',
      items: [
        'designer/deploy/designer',
        'designer/deploy/sandbox',
        'designer/deploy/server',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: '设计器自定义',
      items: [
        'designer/customize/panels',
        'designer/customize/tools',
        'designer/customize/sidebar',
        'designer/customize/setters',
        'designer/customize/editor',
        'designer/customize/components',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: '设计原理',
      items: [
        'designer/design/overview',
        'designer/design/filesystem',
        'designer/design/sandbox',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: '应用框架',
      items: [
        'boot/intro',
        'boot/app-spec',
        'boot/tango-config',
        'boot/app',
        'boot/service',
        'boot/store',
        'boot/page',
        'boot/global',
      ],
      collapsed: false,
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
